FROM ubuntu:precise
MAINTAINER Cristian Romo "cristian.g.romo@gmail.com"

RUN apt-get update && \
  apt-get install \
    g++ \
    libtao-dev \
    libtao-orbsvcs-dev \
    tao-idl \
    -y && \
  rm -rf /var/lib/apt/lists/*
WORKDIR /source
ADD Ping.idl Ping.idl
ADD tao-ping-server.cpp tao-ping-server.cpp
RUN tao_idl Ping.idl && \
  g++ PingC.cpp PingS.cpp tao-ping-server.cpp -lTAO_Valuetype -lTAO_PortableServer -lTAO_IORTable -lTAO_AnyTypeCode -lTAO_CosEvent -lTAO_CosNaming -lTAO -lACE -o tao-ping-server

CMD ["./tao-ping-server", "-ORBDottedDecimalAddresses", "1"]