/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl Ping.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "Ping.h"

#include <stdio.h>

/*** App-specific servant structures ***/

#if !defined(_typedef_impl_POA_Example_Pingable_)
#define _typedef_impl_POA_Example_Pingable_ 1
typedef struct {
POA_Example_Pingable servant;
PortableServer_POA poa;
   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_Example_Pingable;
#endif


/*** Implementation stub prototypes ***/

#if !defined(_decl_impl_Example_Pingable__destroy_)
#define _decl_impl_Example_Pingable__destroy_ 1
static void impl_Example_Pingable__destroy(impl_POA_Example_Pingable *servant,
CORBA_Environment *ev);
#endif

#if !defined(_decl_impl_Example_Pingable_ping_)
#define _decl_impl_Example_Pingable_ping_ 1
static void
impl_Example_Pingable_ping(impl_POA_Example_Pingable *servant,
CORBA_Environment *ev);
#endif


/*** epv structures ***/

#if !defined(_impl_Example_Pingable_base_epv_)
#define _impl_Example_Pingable_base_epv_ 1
static PortableServer_ServantBase__epv impl_Example_Pingable_base_epv = {
NULL,             /* _private data */
(gpointer) & impl_Example_Pingable__destroy, /* finalize routine */
NULL,             /* default_POA routine */
};
#endif

#if !defined(_impl_Example_Pingable_epv_)
#define _impl_Example_Pingable_epv_ 1
static POA_Example_Pingable__epv impl_Example_Pingable_epv = {
NULL, /* _private */
(gpointer)&impl_Example_Pingable_ping,
};
#endif


/*** vepv structures ***/

#if !defined(_impl_Example_Pingable_vepv_)
#define _impl_Example_Pingable_vepv_ 1
static POA_Example_Pingable__vepv impl_Example_Pingable_vepv = {
&impl_Example_Pingable_base_epv,
&impl_Example_Pingable_epv,
};
#endif


/*** Stub implementations ***/

#if !defined(_impl_Example_Pingable__create_)
#define _impl_Example_Pingable__create_ 1
static Example_Pingable impl_Example_Pingable__create(PortableServer_POA poa, CORBA_Environment *ev)
{
Example_Pingable retval;
impl_POA_Example_Pingable *newservant;
PortableServer_ObjectId *objid;

newservant = g_new0(impl_POA_Example_Pingable, 1);
newservant->servant.vepv = &impl_Example_Pingable_vepv;
newservant->poa = (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object)poa, ev);
POA_Example_Pingable__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

objid = PortableServer_POA_activate_object(poa, newservant, ev);
CORBA_free(objid);
retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

return retval;
}
#endif

#if !defined(_impl_Example_Pingable__destroy_)
#define _impl_Example_Pingable__destroy_ 1
static void
impl_Example_Pingable__destroy(impl_POA_Example_Pingable *servant, CORBA_Environment *ev)
{
    CORBA_Object_release ((CORBA_Object) servant->poa, ev);

    /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

POA_Example_Pingable__fini((PortableServer_Servant)servant, ev);

g_free (servant);
}
#endif

#if !defined(_impl_Example_Pingable_ping_)
#define _impl_Example_Pingable_ping_ 1
static void
impl_Example_Pingable_ping(impl_POA_Example_Pingable *servant,
CORBA_Environment *ev)
{
 /* ------   insert method code here   ------ */
    printf("Pinged\n");
 /* ------ ---------- end ------------ ------ */
}
#endif

